services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/laravel-web.site
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
    container_name: app_nginx
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/laravel-web.site
    depends_on:
      - db
    working_dir: /var/www/laravel-web.site
    container_name: app

  db:
    image: mysql:9.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql

    environment:
      MYSQL_DATABASE: laravel-web
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8101:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: app_db



