services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/laravel-web.site
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
    container_name: app_nginx
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/laravel-web.site
    container_name: app

    environment:
      APP_ENV: local
      APP_DEBUG: 1
