name: Build and Push Docker Image

on:
  push:
    branches:
      - develop

env:
  REGISTRY: ghcr.io/laravel-web.site/.guthub/workflows/test-ci.yml
  IMAGE_NAME: app

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозитори
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Логинимся в GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Сборка Docker образа
      - name: Build Docker image
        run: |
          docker build \
            --build-arg NODE_ENV="dev" \
            -t $REGISTRY/$IMAGE_NAME:${GITHUB_SHA} \
            -f ./_docker/gitlab/app/Dockerfile .

      # 4. Push Docker образа
      - name: Push Docker image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${GITHUB_SHA}
